"""updating

Revision ID: f230ebf08716
Revises: d2f3c01a17f0
Create Date: 2019-02-25 15:47:26.788386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f230ebf08716'
down_revision = 'd2f3c01a17f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
